#!/bin/bash

echo "==> Set vlan table"
client_vlan -i 16 -v 0x10c8 -m 0x1fff
client_vlan -i 28 -v 0x10c8 -m 0x1fff

echo "==> Create L2 interface group"
client_group --groupid=0xc80016
client_group --groupid=0xc80016 --l2intfbktid=0 --outport=22 --popvlan=0
client_group --groupid=0xc8001a
client_group --groupid=0xc8001a --l2intfbktid=0 --outport=26 --popvlan=0

echo "==> Create L2 flood group"
client_group --groupid=0x30c80001
client_group --groupid=0x30c80001 --refgroupsbktid=0 --refgroupsrefGID=0xc80016
client_group --groupid=0x30c80001 --refgroupsbktid=1 --refgroupsrefGID=0xc8001a

#echo "==> Set Termination MAC table"
#client_termmac --intf=0 --vlan=200 --dstmac=00:01:02:03:04:05

client_bridging --group=0x30c80001 --dstmac=01:01:02:03:04:05 --vlan=200

